{
 "title": "NOAA Daily Summaries",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station",
    "query": "SELECT station_id FROM public.noaa_station ORDER BY station_id"
   },
   { "name": "interval", "label": "Interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "What was the $interval average high / low?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_date, $interval, NULL),\n  avg(value) as \"Daily High\"\nFROM\n  noaa_daily\nWHERE\n  $__timeFilter(record_date)\nAND \n  station_id = '$station'\nAND\n  datatype = 'TMAX'\nGROUP BY record_date\nORDER BY record_date"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_date, $interval, NULL),\n  avg(value) as \"Daily Low\"\nFROM\n  noaa_daily\nWHERE\n  $__timeFilter(record_date)\nAND \n  station_id = '$station'\nAND\n  datatype = 'TMIN'\nGROUP BY record_date\nORDER BY record_date"
    }
   ]
  },
  {
   "title": "When did it snow?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "yaxes": [
    { "format": "lengthin" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(record_date),\n  value as \"Snowfall\"\nFROM\n  noaa_daily\nWHERE\n  $__timeFilter(record_date)\nAND\n  datatype = 'SNOW'\nORDER BY record_date\n"
    },
    {
     "rawSql": "SELECT\n  $__time(record_date),\n  value as \"Snow on Ground\"\nFROM\n  noaa_daily\nWHERE\n  $__timeFilter(record_date)\nAND\n  datatype = 'SNWD'\nORDER BY record_date\n"
    }
   ]
  },
  {
   "title": "What was the $interval average / total rainfall?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "yaxes": [
    { "format": "lengthin" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_date, $interval, NULL),\n  sum(value) as \"Total Rainfall\"\nFROM\n  noaa_daily\nWHERE\n  $__timeFilter(record_date)\nAND \n  station_id = '$station'\nAND\n  datatype = 'PRCP'\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_date, $interval, NULL),\n  avg(value) as \"Average Rainfall\"\nFROM\n  noaa_daily\nWHERE\n  $__timeFilter(record_date)\nAND \n  station_id = '$station'\nAND\n  datatype = 'PRCP'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Where is $station located?",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  1 as metric,\n  name, \n  latitude,\n  longitude\nFROM\n  public.noaa_station\nWHERE\n  station_id = '$station'\n"
    }
   ]
  }
 ]
}